language: php

sudo: false

git:
  depth: 2

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
      env: PHPSTAN=true LINT=true COVERAGE=true
    - php: 7.1
      env: PHPSTAN=true LINT=true
    - php: 7.2
    - php: nightly
    - php: hhvm
      sudo: required
      dist: trusty
      group: edge
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - source .travis/xdebug.sh
  - xdebug-disable

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist -vvv --profile

script:
  - if [[ $PHPSTAN == "true" ]]; then
      composer require --dev phpstan/phpstan:^0.6 && vendor/bin/phpstan analyse -c phpstan.neon -l 3 src;
    fi
  - if [[ "$LINT" == "true" ]]; then
      composer assert:cs-lint;
      ./bin/travis/lint-docs;
      composer require --dev phpstan/phpstan;
      vendor/bin/phpstan analyse --no-progress --ansi -l 5 lib;
    fi
  - if [[ "$COVERAGE" == "true" ]]; then
      xdebug-enable;
      vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml;
      xdebug-disable;
    else
      vendor/bin/phpunit;
    fi
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml


after_script:
  - if [[ "$COVERAGE" == "true" ]]; then
      php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
    fi

after_success:
  - travis_retry php vendor/bin/coveralls
