language: php

sudo: false

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
      env: PHPSTAN=1
    - php: 7.1
      env: PHPSTAN=1
    - php: hhvm
      sudo: required
      dist: trusty
      group: edge

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - if [[ $PHPSTAN = 1 ]]; then composer require --dev phpstan/phpstan:^0.6 && vendor/bin/phpstan analyse -c phpstan.neon -l 3 src; fi
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml


after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

after_success:
  - travis_retry php vendor/bin/coveralls
